### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Shayan820** [Wishmasterflo/Firmware_flasher#11]
Does the OOS 14 firmware flasher for OnePlus 9 EU removes the bootloader unlocked warning? And can I flash this firmware before flashing any custom rom like Paranoid Android? Because they recommend some other firmware which still have the bootloader unlocked warning... And to remove the bootloader unlocked warning do I have to flash it before or after flashing the rom? Sorry I'm new to OnePlus devices I'm used to Xiaomi devices so that's why I got so many questions  :(

**Comment by Wishmasterflo** [comment]
No the yellow bootloader warning can only be removed on OOS13/OOS13.1 not on OOS14.
And yes normaly when on OOS13/OOS13.1 you flash/sideload the firmware again after the ROM because that file will get overwritten when you install a new custom ROM.
So best is then to flash the firmware before and once after flashing a ROM.
